#!/usr/bin/env node
/**
 * Self-contained build for @smileonroad/dsh-grill-send-button.
 *
 * The sources are TypeScript, so this shells out to esbuild to emit lib/.
 * The installed package ships the prebuilt lib/, so consumers never need a
 * build step. Developers regenerate lib/ with `npm run build` (or the
 * devDependency esbuild resolves locally, or ESBUILD_BIN points at one).
 *
 * Two artifact shapes:
 *
 * - lib/index.js (Host half) — a plain ESM module. The loader imports it the
 *   ordinary way and reads the Cordis-plugin named exports (name / apply).
 *
 * - lib/client.js (browser half) — a dsh client-plugin bundle in the exact
 *   shape the client-modules loader requires: one top-level
 *   `window.__ModuleLoader__.load({ id, factory })` call whose factory is
 *   CommonJS with a synchronous `require` over the module table (react and
 *   friends are platform seed words). esbuild emits the CJS body; this script
 *   wraps it. This mirrors the tsdown client-preset output of the in-box
 *   `@deepseek-ai/dsh-client-ui-*` packages — a bare ESM module never calls
 *   `__ModuleLoader__.load`, so the loader reports "loaded without
 *   registering <id>" and the whole phase batch fails.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

function esbuildPath() {
  if (process.env.ESBUILD_BIN) return process.env.ESBUILD_BIN
  const local = join(root, 'node_modules', 'esbuild', 'bin', 'esbuild')
  if (existsSync(local)) return local
  return 'esbuild' // assume on PATH
}

function compile(entry, outfile, format) {
  execFileSync(process.execPath, [
    esbuildPath(), entry,
    `--outfile=${outfile}`, `--format=${format}`, '--platform=browser', '--target=es2022',
  ], { cwd: root, stdio: 'inherit' })
}

// Host half: ordinary ESM module the loader imports directly.
compile(join(root, 'src', 'host.ts'), join(root, 'lib', 'index.js'), 'esm')

// Client half: CJS body wrapped in the __ModuleLoader__ factory registration.
const tmp = join(root, 'lib', '.client.cjs.tmp')
compile(join(root, 'src', 'index.ts'), tmp, 'cjs')
const body = readFileSync(tmp, 'utf8').trimEnd()
writeFileSync(join(root, 'lib', 'client.js'), [
  '// Generated by scripts/build.mjs — dsh client-plugin bundle (__ModuleLoader__ factory form). Do not edit.',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    const module = { exports: {} };',
  '    const exports = module.exports;',
  '    const React = require("react");',
  body,
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n'))
rmSync(tmp)
console.log('built lib/client.js (loader factory form) and lib/index.js')
