// Generated by scripts/build.mjs — dsh client-plugin bundle (__ModuleLoader__ factory form). Do not edit.
window.__ModuleLoader__.load({
  id: "@smileonroad/dsh-grill-send-button",
  factory: (require) => {
    const module = { exports: {} };
    const exports = module.exports;
    const React = require("react");
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name2 in all)
    __defProp(target, name2, { get: all[name2], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var index_exports = {};
__export(index_exports, {
  GRILL_TRIGGER: () => GRILL_TRIGGER,
  apply: () => apply,
  buildGrillSend: () => buildGrillSend,
  inject: () => inject,
  name: () => name
});
module.exports = __toCommonJS(index_exports);
const GRILL_TRIGGER = "grill me";
function buildGrillSend(busy) {
  if (busy) return null;
  return GRILL_TRIGGER;
}
function apply(ctx) {
  const slots = ctx.get("slots");
  if (slots === void 0) return;
  slots.inject("conversation.input.right", () => slots.register(
    {
      name: "conversation.input.right",
      id: "grill-send",
      order: 1,
      label: () => "Send grill"
    },
    function SendGrillButton(props) {
      const inputActions = props.inputActions;
      const input = props.input;
      const busy = input && (input.phase === "adjudicating" || input.phase === "submitting");
      const message = buildGrillSend(Boolean(busy));
      const onClick = function() {
        if (message === null || !inputActions) return;
        inputActions.setDraft("");
        inputActions.setDraft(message);
        inputActions.submit();
      };
      return React.createElement(
        "button",
        {
          type: "button",
          disabled: message === null,
          title: 'Send the preset message "grill me"',
          onClick,
          style: { marginLeft: "4px", fontSize: "12px" }
        },
        "\u26A1 Grill"
      );
    }
  ));
}
const inject = ["slots"];
const name = "grill-send-button";
    return module.exports;
  },
});
