/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ReplyTipsGetRequest, ReplyTipsGetResult, ReplyTipsSetRequest, ReplyTipsSetResult, ReplyTipsSuggestionsRequest, ReplyTipsSuggestionsResult } from '@smileonroad/dsh-reply-tips/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7265706c7954697073 {
    get: (request: ReplyTipsGetRequest) => Promise<RemoteResult<ReplyTipsGetResult>>
    'get-suggestions': (request: ReplyTipsSuggestionsRequest) => Promise<RemoteResult<ReplyTipsSuggestionsResult>>
    set: (request: ReplyTipsSetRequest) => Promise<RemoteResult<ReplyTipsSetResult>>
  }
  interface TypertRemoteMap {
    'replyTips/get': (request: ReplyTipsGetRequest) => Promise<RemoteResult<ReplyTipsGetResult>>
    'replyTips/get-suggestions': (request: ReplyTipsSuggestionsRequest) => Promise<RemoteResult<ReplyTipsSuggestionsResult>>
    'replyTips/set': (request: ReplyTipsSetRequest) => Promise<RemoteResult<ReplyTipsSetResult>>
  }
  interface TypertRemoteNamespaceMap {
    'replyTips': TypertRemoteNamespace$7265706c7954697073
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
