/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _smileonroad_dsh_reply_tips_replyTips_get_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
})
const _smileonroad_dsh_reply_tips_replyTips_get_result$schema = z.object({
  'enabled': z.boolean().readonly(),
})
const _smileonroad_dsh_reply_tips_replyTips_get_suggestions_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'refresh': z.boolean().readonly(),
})
const _smileonroad_dsh_reply_tips_replyTips_get_suggestions_result$schema = z.object({
  'suggestions': z.array(z.string()).readonly(),
  'reason': z.union([z.literal(null), z.string()]).readonly(),
  'state': z.union([z.literal("idle"), z.literal("generating"), z.literal("fresh")]).readonly(),
})
const _smileonroad_dsh_reply_tips_replyTips_set_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'enabled': z.boolean().readonly(),
})
const _smileonroad_dsh_reply_tips_replyTips_set_result$schema = z.object({
  'enabled': z.boolean().readonly(),
  'saved': z.boolean().readonly(),
})

export const TYPERT = {
  package: '@smileonroad/dsh-reply-tips',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@smileonroad/dsh-reply-tips#replyTips/get',
      service: 'replyTips',
      namespace: 'replyTips',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@smileonroad/dsh-reply-tips/types#ReplyTipsGetRequest',
            schema: _smileonroad_dsh_reply_tips_replyTips_get_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@smileonroad/dsh-reply-tips/types#ReplyTipsGetResult',
        schema: _smileonroad_dsh_reply_tips_replyTips_get_result$schema,
      },
      sourceLocation: {"file":"packages/reply-tips/src/index.ts","line":121,"column":9},
    },
    {
      id: '@smileonroad/dsh-reply-tips#replyTips/get-suggestions',
      service: 'replyTips',
      namespace: 'replyTips',
      method: 'get-suggestions',
      implementation: 'getSuggestions',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@smileonroad/dsh-reply-tips/types#ReplyTipsSuggestionsRequest',
            schema: _smileonroad_dsh_reply_tips_replyTips_get_suggestions_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@smileonroad/dsh-reply-tips/types#ReplyTipsSuggestionsResult',
        schema: _smileonroad_dsh_reply_tips_replyTips_get_suggestions_result$schema,
      },
      sourceLocation: {"file":"packages/reply-tips/src/index.ts","line":147,"column":9},
    },
    {
      id: '@smileonroad/dsh-reply-tips#replyTips/set',
      service: 'replyTips',
      namespace: 'replyTips',
      method: 'set',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@smileonroad/dsh-reply-tips/types#ReplyTipsSetRequest',
            schema: _smileonroad_dsh_reply_tips_replyTips_set_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@smileonroad/dsh-reply-tips/types#ReplyTipsSetResult',
        schema: _smileonroad_dsh_reply_tips_replyTips_set_result$schema,
      },
      sourceLocation: {"file":"packages/reply-tips/src/index.ts","line":133,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "reply-tips 的 Host 服务：开关真源与建议生成。",
        "summary": "reply-tips 的 Host 服务：开关真源与建议生成。",
        "tags": [],
        "jsDoc": "/** reply-tips 的 Host 服务：开关真源与建议生成。 */",
        "key": "replyTips",
        "exportName": "ReplyTipsService",
        "members": [
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') async get(request: ReplyTipsGetRequest): Promise<ReplyTipsGetResult>",
            "summary": "读开关（mem 优先，miss 读会话工作区文件）。",
            "jsDoc": "/**\n * 读开关（mem 优先，miss 读会话工作区文件）。\n * @param request - 目标会话。\n * @returns 当前开关值。\n */"
          },
          {
            "kind": "method",
            "name": "set",
            "signature": "@Remote('set') async set(request: ReplyTipsSetRequest): Promise<ReplyTipsSetResult>",
            "summary": "写开关（乐观写 mem + fs 落盘）。",
            "jsDoc": "/**\n * 写开关（乐观写 mem + fs 落盘）。\n * @param request - 目标会话与目标状态。\n * @returns 落定状态与落盘结果。\n */"
          },
          {
            "kind": "method",
            "name": "getSuggestions",
            "signature": "@Remote('get-suggestions') async getSuggestions(request: ReplyTipsSuggestionsRequest): Promise<ReplyTipsSuggestionsResult>",
            "summary": "取追问建议（回合结束边沿 refresh 或轮询 poll）。",
            "jsDoc": "/**\n * 取追问建议（回合结束边沿 refresh 或轮询 poll）。\n * @param request - 目标会话与刷新标记。\n * @returns 建议、失败原因与交付状态。\n */"
          }
        ],
        "types": [
          {
            "name": "ReplyTipsGetRequest",
            "declaration": "export interface ReplyTipsGetRequest {\n    readonly sessionId: string;\n}"
          },
          {
            "name": "ReplyTipsGetResult",
            "declaration": "export interface ReplyTipsGetResult {\n    readonly enabled: boolean;\n}"
          },
          {
            "name": "ReplyTipsSetRequest",
            "declaration": "export interface ReplyTipsSetRequest {\n    readonly sessionId: string;\n    readonly enabled: boolean;\n}"
          },
          {
            "name": "ReplyTipsSetResult",
            "declaration": "export interface ReplyTipsSetResult {\n    readonly enabled: boolean;\n    readonly saved: boolean;\n}"
          },
          {
            "name": "ReplyTipsState",
            "declaration": "export type ReplyTipsState = 'idle' | 'generating' | 'fresh';"
          },
          {
            "name": "ReplyTipsSuggestionsRequest",
            "declaration": "export interface ReplyTipsSuggestionsRequest {\n    readonly sessionId: string;\n    readonly refresh: boolean;\n}"
          },
          {
            "name": "ReplyTipsSuggestionsResult",
            "declaration": "export interface ReplyTipsSuggestionsResult {\n    readonly suggestions: readonly string[];\n    readonly reason: string | null;\n    readonly state: ReplyTipsState;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
